# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js versi sesuai matriks dan cache npm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3. Install dependencies menggunakan npm ci (memerlukan package-lock.json)
      - name: Install dependencies
        run: npm ci
        working-directory: ./your-directory  # Ganti dengan direktori proyek kamu jika diperlukan

      # 4. Build proyek jika ada script build
      - name: Build project
        run: npm run build --if-present
        working-directory: ./your-directory  # Ganti dengan direktori proyek kamu jika diperlukan

      # 5. Jalankan tes
      - name: Run tests
        run: npm test
        working-directory: ./your-directory  # Ganti dengan direktori proyek kamu jika diperlukan
